CREATE TABLE "ChatFiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer,
    "GroupId" integer,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatFiles" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Image" text NOT NULL,
    "Name" text NOT NULL,
    "Bio" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsEmailVerified" boolean NOT NULL,
    "EmailVerificationToken" text,
    "EmailVerificationTokenExpiresAt" timestamp with time zone,
    "ResetPasswordToken" text,
    "ResetPasswordTokenExpiresAt" timestamp with time zone,
    "LaughScore" integer NOT NULL,
    "LastLaughScoreUpdate" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "FriendRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_FriendRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FriendRequests_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FriendRequests_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Groups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CreatedById" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Groups_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "NotificationPreferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EmailNotifications" boolean NOT NULL,
    "PushNotifications" boolean NOT NULL,
    "InAppNotifications" boolean NOT NULL,
    "LikeNotifications" boolean NOT NULL,
    "CommentNotifications" boolean NOT NULL,
    "FollowNotifications" boolean NOT NULL,
    "MentionNotifications" boolean NOT NULL,
    "ShareNotifications" boolean NOT NULL,
    "FriendRequestNotifications" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificationPreferences_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Posts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Image" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupMemberships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_GroupMemberships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupMemberships_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupMemberships_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer,
    "GroupId" integer,
    "Content" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "EditedAt" timestamp with time zone,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id"),
    CONSTRAINT "FK_Messages_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ParentCommentId" integer,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Comments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "Comments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Reactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reactions_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "SharedPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "SharedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SharedPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedPosts_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SharedPosts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MessageReactons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "ReactorId" integer NOT NULL,
    "Emoji" text NOT NULL,
    CONSTRAINT "PK_MessageReactons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageReactons_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MessageReactons_Users_ReactorId" FOREIGN KEY ("ReactorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MessageReadReceipts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "SeenAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MessageReadReceipts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageReadReceipts_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MessageReadReceipts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "Title" character varying(100),
    "RelatedUserId" integer,
    "PostId" integer,
    "CommentId" integer,
    "ActionUrl" character varying(200),
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Priority" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id"),
    CONSTRAINT "FK_Notifications_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id"),
    CONSTRAINT "FK_Notifications_Users_RelatedUserId" FOREIGN KEY ("RelatedUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Comments_ParentCommentId" ON "Comments" ("ParentCommentId");


CREATE INDEX "IX_Comments_PostId" ON "Comments" ("PostId");


CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");


CREATE INDEX "IX_FriendRequests_ReceiverId" ON "FriendRequests" ("ReceiverId");


CREATE INDEX "IX_FriendRequests_SenderId" ON "FriendRequests" ("SenderId");


CREATE INDEX "IX_GroupMemberships_GroupId" ON "GroupMemberships" ("GroupId");


CREATE INDEX "IX_GroupMemberships_UserId" ON "GroupMemberships" ("UserId");


CREATE INDEX "IX_Groups_CreatedById" ON "Groups" ("CreatedById");


CREATE INDEX "IX_MessageReactons_MessageId" ON "MessageReactons" ("MessageId");


CREATE INDEX "IX_MessageReactons_ReactorId" ON "MessageReactons" ("ReactorId");


CREATE INDEX "IX_MessageReadReceipts_MessageId" ON "MessageReadReceipts" ("MessageId");


CREATE INDEX "IX_MessageReadReceipts_UserId" ON "MessageReadReceipts" ("UserId");


CREATE INDEX "IX_Messages_GroupId" ON "Messages" ("GroupId");


CREATE INDEX "IX_Messages_ReceiverId" ON "Messages" ("ReceiverId");


CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");


CREATE INDEX "IX_NotificationPreferences_UserId" ON "NotificationPreferences" ("UserId");


CREATE INDEX "IX_Notifications_CommentId" ON "Notifications" ("CommentId");


CREATE INDEX "IX_Notifications_PostId" ON "Notifications" ("PostId");


CREATE INDEX "IX_Notifications_RelatedUserId" ON "Notifications" ("RelatedUserId");


CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");


CREATE INDEX "IX_Posts_UserId" ON "Posts" ("UserId");


CREATE INDEX "IX_Reactions_PostId" ON "Reactions" ("PostId");


CREATE INDEX "IX_Reactions_UserId" ON "Reactions" ("UserId");


CREATE INDEX "IX_SharedPosts_PostId" ON "SharedPosts" ("PostId");


CREATE INDEX "IX_SharedPosts_UserId" ON "SharedPosts" ("UserId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


