using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemeStreamApi.Migrations
{
    /// <inheritdoc />
    public partial class AddMessageReadReceipts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if the table already exists before creating it
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM information_schema.tables
                                  WHERE table_name = 'MessageReadReceipts') THEN
                        CREATE TABLE ""MessageReadReceipts"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""MessageId"" integer NOT NULL,
                            ""UserId"" integer NOT NULL,
                            ""SeenAt"" timestamp with time zone NOT NULL,
                            CONSTRAINT ""PK_MessageReadReceipts"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_MessageReadReceipts_Messages_MessageId"" FOREIGN KEY (""MessageId"") REFERENCES ""Messages"" (""Id"") ON DELETE CASCADE,
                            CONSTRAINT ""FK_MessageReadReceipts_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                        );

                        CREATE INDEX ""IX_MessageReadReceipts_MessageId"" ON ""MessageReadReceipts"" (""MessageId"");
                        CREATE INDEX ""IX_MessageReadReceipts_UserId"" ON ""MessageReadReceipts"" (""UserId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MessageReadReceipts");
        }
    }
}
